// Demo data for the Espace Médecin — Dr. Arnaud Akwétéy DANSOU
import type {
    Doctor,
    Payment,
    Notification,
    Application,
    DocumentRequest,
    Verification,
    DossierDocument,
} from "@/types/medecin";

export const DEMO_DOCTOR: Doctor = {
    id: "demo-doc-001",
    user_id: "demo-user-001",
    numero_ordre: 1547,
    nom: "DANSOU",
    prenoms: "Arnaud Akwétéy",
    genre: "M",
    specialite_principale: "Médecine Générale",
    ville_exercice: "Libreville",
    province: "Estuaire",
    adresse_cabinet: "Quartier Glass, Rue du CHU, Libreville",
    coordonnees_gps: { lat: 0.4162, lng: 9.4673 },
    telephone_pro: "+241 74 00 15 47",
    email: "a.dansou@cnom-gabon.ga",
    secteur_exercice: "Public",
    etablissement: "CHU de Libreville",
    statut: "Inscrit",
    date_inscription: "2019-03-15",
    diplome_principal: "Doctorat en Médecine",
    universite_obtention: "Université des Sciences de la Santé (USS)",
    annee_obtention: 2018,
    fonctions_ordinales: "Membre",
    photo_url: undefined, // Will use imported asset
    created_at: "2019-03-15T08:00:00Z",
    updated_at: "2026-01-10T14:30:00Z",
};

export const DEMO_APPLICATION: Application = {
    id: "demo-app-001",
    user_id: "demo-user-001",
    status: "validated",
    step_current: 6,
    step_total: 6,
    numero_ordre_attribue: 1547,
    is_etranger: false,
    data: {
        nom: "DANSOU",
        prenoms: "Arnaud Akwétéy",
        date_naissance: "1992-05-10",
        nationalite: "Gabonaise",
    },
    created_at: "2019-02-01T08:00:00Z",
    updated_at: "2019-03-15T14:30:00Z",
};

export const DEMO_PAYMENTS: Payment[] = [
    {
        id: "pay-001",
        doctor_id: "demo-doc-001",
        type: "cotisation_semestrielle",
        montant: 60000,
        moyen_paiement: "airtel_money",
        reference_transaction: "TXN-2026-0042",
        periode_couverte_debut: "2026-01-01",
        periode_couverte_fin: "2026-06-30",
        statut: "confirme",
        recu_pdf_url: "#",
        created_at: "2026-01-15T10:30:00Z",
    },
    {
        id: "pay-002",
        doctor_id: "demo-doc-001",
        type: "cotisation_semestrielle",
        montant: 60000,
        moyen_paiement: "moov_money",
        reference_transaction: "TXN-2025-0189",
        periode_couverte_debut: "2025-07-01",
        periode_couverte_fin: "2025-12-31",
        statut: "confirme",
        recu_pdf_url: "#",
        created_at: "2025-07-01T09:15:00Z",
    },
    {
        id: "pay-003",
        doctor_id: "demo-doc-001",
        type: "cotisation_semestrielle",
        montant: 60000,
        moyen_paiement: "carte_bancaire",
        reference_transaction: "TXN-2025-0011",
        periode_couverte_debut: "2025-01-01",
        periode_couverte_fin: "2025-06-30",
        statut: "confirme",
        recu_pdf_url: "#",
        created_at: "2025-01-15T14:00:00Z",
    },
    {
        id: "pay-004",
        doctor_id: "demo-doc-001",
        type: "inscription",
        montant: 50000,
        moyen_paiement: "airtel_money",
        reference_transaction: "TXN-2019-0001",
        statut: "confirme",
        recu_pdf_url: "#",
        created_at: "2019-03-10T11:00:00Z",
    },
];

export const DEMO_NOTIFICATIONS: Notification[] = [
    {
        id: "notif-001",
        doctor_id: "demo-doc-001",
        type: "paiement",
        titre: "Cotisation S1 2026 confirmée",
        message: "Votre paiement de 60 000 FCFA pour le premier semestre 2026 a été confirmé. Reçu disponible.",
        lue: false,
        lien_action: "/medecin/paiements",
        created_at: "2026-01-15T10:35:00Z",
    },
    {
        id: "notif-002",
        doctor_id: "demo-doc-001",
        type: "carte",
        titre: "Carte e-CPS renouvelée",
        message: "Votre carte professionnelle virtuelle a été renouvelée pour l'année 2026.",
        lue: false,
        lien_action: "/medecin/ecps",
        created_at: "2026-01-10T08:00:00Z",
    },
    {
        id: "notif-003",
        doctor_id: "demo-doc-001",
        type: "ordre",
        titre: "Communiqué du Conseil National",
        message: "Le Conseil National de l'Ordre des Médecins vous informe de la tenue de l'Assemblée Générale le 15 mars 2026.",
        lue: false,
        lien_action: undefined,
        created_at: "2026-01-08T15:00:00Z",
    },
    {
        id: "notif-004",
        doctor_id: "demo-doc-001",
        type: "paiement",
        titre: "Rappel : Cotisation S2 2026",
        message: "Votre cotisation pour le second semestre 2026 sera due le 30 juin 2026. Montant : 60 000 FCFA.",
        lue: true,
        lien_action: "/medecin/paiements",
        created_at: "2026-01-05T09:00:00Z",
    },
    {
        id: "notif-005",
        doctor_id: "demo-doc-001",
        type: "systeme",
        titre: "Maintenance programmée",
        message: "Une maintenance du portail est prévue le 20 février 2026 de 02h à 06h (heure de Libreville).",
        lue: true,
        created_at: "2025-12-20T10:00:00Z",
    },
    {
        id: "notif-006",
        doctor_id: "demo-doc-001",
        type: "dossier",
        titre: "Dossier complété et validé",
        message: "Votre dossier d'inscription au Tableau de l'Ordre a été validé. N° d'Ordre attribué : 1547.",
        lue: true,
        created_at: "2019-03-15T14:30:00Z",
    },
];

export const DEMO_DOCUMENT_REQUESTS: DocumentRequest[] = [
    {
        id: "docreq-001",
        doctor_id: "demo-doc-001",
        type: "attestation_inscription",
        statut: "disponible",
        document_genere_url: "#",
        created_at: "2026-02-01T10:00:00Z",
        processed_at: "2026-02-02T09:30:00Z",
    },
    {
        id: "docreq-002",
        doctor_id: "demo-doc-001",
        type: "attestation_bonne_conduite",
        motif: "Démarche administrative",
        statut: "disponible",
        document_genere_url: "#",
        created_at: "2025-12-15T11:00:00Z",
        processed_at: "2025-12-18T16:00:00Z",
    },
];

export const DEMO_VERIFICATIONS: Verification[] = [
    {
        id: "verif-001",
        doctor_id: "demo-doc-001",
        localisation_approx: "Libreville, Gabon",
        resultat: "inscrit",
        created_at: "2026-02-08T14:32:00Z",
    },
    {
        id: "verif-002",
        doctor_id: "demo-doc-001",
        localisation_approx: "Port-Gentil, Gabon",
        resultat: "inscrit",
        created_at: "2026-02-05T09:15:00Z",
    },
    {
        id: "verif-003",
        doctor_id: "demo-doc-001",
        localisation_approx: "Franceville, Gabon",
        resultat: "inscrit",
        created_at: "2026-01-28T11:45:00Z",
    },
];

export const DEMO_DOSSIER_DOCUMENTS: DossierDocument[] = [
    { id: "dd-1", type: "diplome", nom_fichier: "diplome_medecine_2018.pdf", statut_verification: "verifie" },
    { id: "dd-2", type: "casier_judiciaire", nom_fichier: "casier_judiciaire.pdf", statut_verification: "verifie" },
    { id: "dd-3", type: "photo_identite", nom_fichier: "photo_identite.jpg", statut_verification: "verifie" },
    { id: "dd-4", type: "piece_identite", nom_fichier: "cni_gabon.pdf", statut_verification: "verifie" },
];
